id: 6b309d6721b9493fbfec3e0bd72cfc8b
initial_creation_type: ocr
source_metadata:
  volumes:
    5f313c544576456b8fac80f1892f1b8e:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: བྱང་ཆུབ་ཀྱི་ལྟུང་བ་བཤགས་པའི་འགྲེལ་པ།
      total_pages: 1529
      volume_number: 67
